NOM_ETABLISSEMENT=""
MODIF_SECRETARIAT_COLLOSCOPE=True
MODIF_PROF_COLLOSCOPE=True
MODIF_SECRETARIAT_GROUPE=False
MODIF_PROF_GROUPE=True
DEFAULT_MODIF_COLLOSCOPE=False
DEFAULT_MODIF_GROUPE=False
MATHJAX=False
ECTS=True
NOM_ADRESSE_ETABLISSEMENT="""Lycée général et technologique Léon Gontran Damas
chemin Vidal
97354 Rémire-Montjoly"""
VILLE="Rémire-Montjoly"
ACADEMIE="Guyane"