# Generated by Django 2.2.3 on 2019-07-26 20:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0010_creation_css-comptes'),
    ]

    operations = [
        migrations.AddField(
            model_name='decompte',
            name='mois',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='decompte',
            name='colleur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.Colleur'),
        ),
        migrations.AlterField(
            model_name='semaine',
            name='lundi',
            field=models.DateField(choices=[(datetime.date(2018, 10, 15), '15 十月 2018'), (datetime.date(2018, 10, 22), '22 十月 2018'), (datetime.date(2018, 10, 29), '29 十月 2018'), (datetime.date(2018, 11, 5), '05 十一月 2018'), (datetime.date(2018, 11, 12), '12 十一月 2018'), (datetime.date(2018, 11, 19), '19 十一月 2018'), (datetime.date(2018, 11, 26), '26 十一月 2018'), (datetime.date(2018, 12, 3), '03 十二月 2018'), (datetime.date(2018, 12, 10), '10 十二月 2018'), (datetime.date(2018, 12, 17), '17 十二月 2018'), (datetime.date(2018, 12, 24), '24 十二月 2018'), (datetime.date(2018, 12, 31), '31 十二月 2018'), (datetime.date(2019, 1, 7), '07 一月 2019'), (datetime.date(2019, 1, 14), '14 一月 2019'), (datetime.date(2019, 1, 21), '21 一月 2019'), (datetime.date(2019, 1, 28), '28 一月 2019'), (datetime.date(2019, 2, 4), '04 二月 2019'), (datetime.date(2019, 2, 11), '11 二月 2019'), (datetime.date(2019, 2, 18), '18 二月 2019'), (datetime.date(2019, 2, 25), '25 二月 2019'), (datetime.date(2019, 3, 4), '04 三月 2019'), (datetime.date(2019, 3, 11), '11 三月 2019'), (datetime.date(2019, 3, 18), '18 三月 2019'), (datetime.date(2019, 3, 25), '25 三月 2019'), (datetime.date(2019, 4, 1), '01 四月 2019'), (datetime.date(2019, 4, 8), '08 四月 2019'), (datetime.date(2019, 4, 15), '15 四月 2019'), (datetime.date(2019, 4, 22), '22 四月 2019'), (datetime.date(2019, 4, 29), '29 四月 2019'), (datetime.date(2019, 5, 6), '06 五月 2019'), (datetime.date(2019, 5, 13), '13 五月 2019'), (datetime.date(2019, 5, 20), '20 五月 2019'), (datetime.date(2019, 5, 27), '27 五月 2019'), (datetime.date(2019, 6, 3), '03 六月 2019'), (datetime.date(2019, 6, 10), '10 六月 2019'), (datetime.date(2019, 6, 17), '17 六月 2019'), (datetime.date(2019, 6, 24), '24 六月 2019'), (datetime.date(2019, 7, 1), '01 七月 2019'), (datetime.date(2019, 7, 8), '08 七月 2019'), (datetime.date(2019, 7, 15), '15 七月 2019'), (datetime.date(2019, 7, 22), '22 七月 2019'), (datetime.date(2019, 7, 29), '29 七月 2019'), (datetime.date(2019, 8, 5), '05 八月 2019'), (datetime.date(2019, 8, 12), '12 八月 2019'), (datetime.date(2019, 8, 19), '19 八月 2019'), (datetime.date(2019, 8, 26), '26 八月 2019'), (datetime.date(2019, 9, 2), '02 九月 2019'), (datetime.date(2019, 9, 9), '09 九月 2019'), (datetime.date(2019, 9, 16), '16 九月 2019'), (datetime.date(2019, 9, 23), '23 九月 2019'), (datetime.date(2019, 9, 30), '30 九月 2019'), (datetime.date(2019, 10, 7), '07 十月 2019'), (datetime.date(2019, 10, 14), '14 十月 2019'), (datetime.date(2019, 10, 21), '21 十月 2019'), (datetime.date(2019, 10, 28), '28 十月 2019'), (datetime.date(2019, 11, 4), '04 十一月 2019'), (datetime.date(2019, 11, 11), '11 十一月 2019'), (datetime.date(2019, 11, 18), '18 十一月 2019'), (datetime.date(2019, 11, 25), '25 十一月 2019'), (datetime.date(2019, 12, 2), '02 十二月 2019'), (datetime.date(2019, 12, 9), '09 十二月 2019'), (datetime.date(2019, 12, 16), '16 十二月 2019'), (datetime.date(2019, 12, 23), '23 十二月 2019'), (datetime.date(2019, 12, 30), '30 十二月 2019'), (datetime.date(2020, 1, 6), '06 一月 2020'), (datetime.date(2020, 1, 13), '13 一月 2020'), (datetime.date(2020, 1, 20), '20 一月 2020'), (datetime.date(2020, 1, 27), '27 一月 2020'), (datetime.date(2020, 2, 3), '03 二月 2020'), (datetime.date(2020, 2, 10), '10 二月 2020'), (datetime.date(2020, 2, 17), '17 二月 2020'), (datetime.date(2020, 2, 24), '24 二月 2020'), (datetime.date(2020, 3, 2), '02 三月 2020'), (datetime.date(2020, 3, 9), '09 三月 2020'), (datetime.date(2020, 3, 16), '16 三月 2020'), (datetime.date(2020, 3, 23), '23 三月 2020'), (datetime.date(2020, 3, 30), '30 三月 2020'), (datetime.date(2020, 4, 6), '06 四月 2020'), (datetime.date(2020, 4, 13), '13 四月 2020'), (datetime.date(2020, 4, 20), '20 四月 2020'), (datetime.date(2020, 4, 27), '27 四月 2020'), (datetime.date(2020, 5, 4), '04 五月 2020'), (datetime.date(2020, 5, 11), '11 五月 2020'), (datetime.date(2020, 5, 18), '18 五月 2020'), (datetime.date(2020, 5, 25), '25 五月 2020'), (datetime.date(2020, 6, 1), '01 六月 2020'), (datetime.date(2020, 6, 8), '08 六月 2020'), (datetime.date(2020, 6, 15), '15 六月 2020'), (datetime.date(2020, 6, 22), '22 六月 2020'), (datetime.date(2020, 6, 29), '29 六月 2020'), (datetime.date(2020, 7, 6), '06 七月 2020'), (datetime.date(2020, 7, 13), '13 七月 2020'), (datetime.date(2020, 7, 20), '20 七月 2020'), (datetime.date(2020, 7, 27), '27 七月 2020'), (datetime.date(2020, 8, 3), '03 八月 2020'), (datetime.date(2020, 8, 10), '10 八月 2020'), (datetime.date(2020, 8, 17), '17 八月 2020'), (datetime.date(2020, 8, 24), '24 八月 2020'), (datetime.date(2020, 8, 31), '31 八月 2020'), (datetime.date(2020, 9, 7), '07 九月 2020')], default=datetime.date(2019, 7, 22), unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='css',
            field=models.CharField(choices=[('style.css', 'classique'), ('new_style.css', 'épuré')], default='style.css', max_length=50, verbose_name='Style préféré'),
        ),
        migrations.AlterUniqueTogether(
            name='decompte',
            unique_together={('colleur', 'classe', 'matiere', 'ramassage', 'mois')},
        ),
    ]
