# Generated by Django 2.2.3 on 2019-08-06 19:32

import accueil.models.autre
import accueil.models.contenttype
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0013_auto_20190803_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='fichier',
            field=accueil.models.contenttype.ContentTypeRestrictedFileField(blank=True, null=True, upload_to=accueil.models.autre.Programme.update_name, verbose_name='Fichier(pdf)'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='semaine',
            field=models.ManyToManyField(to='accueil.Semaine', verbose_name='Semaine(s)'),
        ),
        migrations.AlterField(
            model_name='ramassage',
            name='moisFin',
            field=models.DateField(unique=True, verbose_name="Jusqu'à (inclus)"),
        ),
        migrations.AlterField(
            model_name='semaine',
            name='lundi',
            field=models.DateField(unique=True),
        ),
    ]
