# Generated by Django 2.2.3 on 2019-08-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0014_auto_20190806_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='message_eleves',
            field=models.BooleanField(default=False, verbose_name='Autoriser les étudiants à écrire aux colleurs (pas seulement répondre)'),
        ),
        migrations.AlterField(
            model_name='semaine',
            name='numero',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36)], default=1, unique=True),
        ),
    ]
