# Generated by Django 3.0 on 2020-07-28 02:53

import accueil.models.contenttype
import accueil.models.devoir
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0015_auto_20190821_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devoir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (66, 66), (67, 67), (68, 68), (69, 69), (70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85), (86, 86), (87, 87), (88, 88), (89, 89), (90, 90), (91, 91), (92, 92), (93, 93), (94, 94), (95, 95), (96, 96), (97, 97), (98, 98), (99, 99), (100, 100)], verbose_name='Numéro')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Détails')),
                ('date_affichage', models.DateTimeField(auto_now_add=True)),
                ('a_rendre_jour', models.DateField(blank=True, null=True, verbose_name='à rendre le ')),
                ('a_rendre_heure', models.TimeField(blank=True, choices=[(datetime.time(0, 0), ' 0h00'), (datetime.time(1, 0), ' 1h00'), (datetime.time(2, 0), ' 2h00'), (datetime.time(3, 0), ' 3h00'), (datetime.time(4, 0), ' 4h00'), (datetime.time(5, 0), ' 5h00'), (datetime.time(6, 0), ' 6h00'), (datetime.time(7, 0), ' 7h00'), (datetime.time(8, 0), ' 8h00'), (datetime.time(9, 0), ' 9h00'), (datetime.time(10, 0), '10h00'), (datetime.time(11, 0), '11h00'), (datetime.time(12, 0), '12h00'), (datetime.time(13, 0), '13h00'), (datetime.time(14, 0), '14h00'), (datetime.time(15, 0), '15h00'), (datetime.time(16, 0), '16h00'), (datetime.time(17, 0), '17h00'), (datetime.time(18, 0), '18h00'), (datetime.time(19, 0), '19h00'), (datetime.time(20, 0), '20h00'), (datetime.time(21, 0), '21h00'), (datetime.time(22, 0), '22h00'), (datetime.time(23, 0), '23h00')], null=True, verbose_name='à')),
                ('fichier', accueil.models.contenttype.ContentTypeRestrictedFileField(blank=True, null=True, upload_to=accueil.models.devoir.Devoir.update_name, verbose_name='Fichier(pdf)')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classedevoir', to='accueil.Classe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matieredevoir', to='accueil.Matiere')),
            ],
            options={
                'ordering': ['date_affichage'],
                'unique_together': {('numero', 'classe', 'matiere')},
            },
        ),
        migrations.CreateModel(
            name='DevoirRendu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rendu', models.DateTimeField(auto_now_add=True)),
                ('fichier', accueil.models.contenttype.ContentTypeRestrictedFileField(blank=True, null=True, upload_to=accueil.models.devoir.DevoirRendu.update_name, verbose_name='Fichier(pdf)')),
                ('devoir', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rendus', to='accueil.Devoir')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoireleve', to='accueil.Eleve')),
            ],
            options={
                'ordering': ['date_rendu'],
                'unique_together': {('eleve', 'devoir')},
            },
        ),
        migrations.CreateModel(
            name='DevoirCorrige',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('fichier', accueil.models.contenttype.ContentTypeRestrictedFileField(blank=True, null=True, upload_to=accueil.models.devoir.DevoirCorrige.update_name, verbose_name='Fichier(pdf)')),
                ('devoir', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrigés', to='accueil.Devoir')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoircorrigeeleve', to='accueil.Eleve')),
            ],
            options={
                'ordering': ['eleve__user__last_name', 'eleve__user__first_name'],
                'unique_together': {('eleve', 'devoir')},
            },
        ),
    ]
