# Generated by Django 3.0 on 2020-07-29 14:21

import accueil.models.contenttype
import accueil.models.devoir
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0016_devoir_devoircorrige_devoirrendu'),
    ]

    operations = [
        migrations.AddField(
            model_name='devoir',
            name='corrige',
            field=accueil.models.contenttype.ContentTypeRestrictedFileField(blank=True, null=True, upload_to=accueil.models.devoir.Devoir.update_name, verbose_name='Corrigé(pdf)'),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='fichier',
            field=accueil.models.contenttype.ContentTypeRestrictedFileField(blank=True, null=True, upload_to=accueil.models.devoir.Devoir.update_name, verbose_name='Énoncé(pdf)'),
        ),
    ]
