# Generated by Django 3.0 on 2020-08-17 00:20

import accueil.models.autre
import accueil.models.contenttype
import accueil.models.devoir
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0017_auto_20200729_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='pj',
            field=accueil.models.contenttype.ContentTypeRestrictedFileField(blank=True, null=True, upload_to=accueil.models.autre.Message.update_name, verbose_name='Pièce jointe'),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='corrige',
            field=accueil.models.contenttype.ContentTypeRestrictedFileField(blank=True, null=True, upload_to=accueil.models.devoir.Devoir.update_name_corrige, verbose_name='Corrigé(pdf)'),
        ),
        migrations.AlterField(
            model_name='devoirrendu',
            name='date_rendu',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
