# Generated by Django 3.1 on 2021-01-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0019_auto_20200903_0006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colleur',
            options={'ordering': ['user__last_name', 'user__first_name']},
        ),
        migrations.AlterField(
            model_name='decompte',
            name='temps',
            field=models.IntegerField(default=0),
        ),
    ]
