# Generated by Django 3.1 on 2021-08-01 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0020_auto_20210122_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='option1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classeoption1', to='accueil.matiere'),
        ),
        migrations.AddField(
            model_name='classe',
            name='option2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classeoption2', to='accueil.matiere'),
        ),
        migrations.AddField(
            model_name='classe',
            name='semestres',
            field=models.BooleanField(default=False, verbose_name='Groupes différents les 2 semestres'),
        ),
        migrations.AddField(
            model_name='config',
            name='semestre2',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='début du second semestre'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='groupe2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupe2eleve', to='accueil.groupe'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleveoption', to='accueil.matiere'),
        ),
    ]
