# Generated by Django 3.1 on 2021-08-10 02:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0021_auto_20210801_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediteur', models.PositiveSmallIntegerField(choices=[(1, 'Administrateur'), (2, 'Secrétariat')], default=1, verbose_name='Expéditeur')),
                ('destinataire', models.PositiveSmallIntegerField(choices=[(1, 'Colleurs'), (2, 'Élèves'), (3, 'Tout le monde')], verbose_name='destinataires')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='corps',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2000, null=True),
        ),
    ]
