# Generated by Django 3.2.6 on 2021-09-30 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0023_alter_devoircorrige_devoir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='option1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classeoption1', to='accueil.matiere'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='option2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classeoption2', to='accueil.matiere'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='temps',
            field=models.PositiveSmallIntegerField(choices=[(20, '20 min (par groupe de 3)'), (30, '30 min (solo)'), (45, '45 min (solo)'), (60, '60 min (informatique)')], default=20, verbose_name='minutes/colle/élève'),
        ),
    ]
