# Generated by Django 3.2.6 on 2022-01-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0024_auto_20210930_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='temps',
            field=models.PositiveSmallIntegerField(choices=[(5, '5 min'), (10, '10 min'), (15, '15 min'), (20, '20 min'), (25, '25 min'), (30, '30 min'), (35, '35 min'), (40, '40 min'), (45, '45 min'), (50, '50 min'), (55, '55 min'), (60, '60 min')], default=20, verbose_name='minutes/colle/élève'),
        ),
    ]
