# Generated by Django 4.1 on 2022-08-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0025_alter_matiere_temps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devoir',
            options={'ordering': ['-numero']},
        ),
        migrations.AlterField(
            model_name='matiere',
            name='temps',
            field=models.PositiveSmallIntegerField(choices=[(0, '0 min'), (5, '5 min'), (10, '10 min'), (15, '15 min'), (20, '20 min'), (25, '25 min'), (30, '30 min'), (35, '35 min'), (40, '40 min'), (45, '45 min'), (50, '50 min'), (55, '55 min'), (60, '60 min'), (65, '65 min'), (70, '70 min'), (75, '75 min'), (80, '80 min'), (85, '85 min'), (90, '90 min'), (95, '95 min'), (100, '100 min'), (105, '105 min'), (110, '110 min'), (115, '115 min'), (120, '120 min')], default=20, verbose_name='minutes/colle/élève'),
        ),
    ]
