# Generated by Django 4.1 on 2023-05-15 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0026_alter_devoir_options_alter_matiere_temps'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='ects_modif',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Personne'), (1, 'Professeur principal'), (2, 'Secrétariat'), (3, 'Les 2')], default=1, verbose_name='droit de modification sur les matières/coefficients ECTS'),
        ),
    ]
