# Generated by Django 4.2.4 on 2024-05-12 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0029_td_corrige'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='planche',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.CreateModel(
            name='Planche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.CharField(blank=True, max_length=100, null=True)),
                ('jour', models.PositiveSmallIntegerField(choices=[(0, 'lundi'), (1, 'mardi'), (2, 'mercredi'), (3, 'jeudi'), (4, 'vendredi'), (5, 'samedi')], default=0)),
                ('heure', models.PositiveSmallIntegerField(choices=[(480, '8h00'), (510, '8h30'), (540, '9h00'), (570, '9h30'), (600, '10h00'), (630, '10h30'), (660, '11h00'), (690, '11h30'), (720, '12h00'), (750, '12h30'), (780, '13h00'), (810, '13h30'), (840, '14h00'), (870, '14h30'), (900, '15h00'), (930, '15h30'), (960, '16h00'), (990, '16h30'), (1020, '17h00'), (1050, '17h30'), (1080, '18h00'), (1110, '18h30'), (1140, '19h00'), (1170, '19h30')], default=480)),
                ('salle', models.CharField(blank=True, max_length=20, null=True)),
                ('classes', models.ManyToManyField(to='accueil.classe', verbose_name='Classe(s)')),
                ('colleur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planchecolleur', to='accueil.colleur', verbose_name='Colleur')),
                ('eleve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plancheeleve', to='accueil.eleve')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planchematiere', to='accueil.matiere')),
                ('semaine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planchesemaine', to='accueil.semaine')),
            ],
            options={
                'ordering': ['matiere__nom', 'colleur__user__last_name', 'colleur__user__first_name', 'semaine__numero', 'jour', 'heure'],
            },
        ),
    ]
