# Generated by Django 4.2.4 on 2025-05-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0030_matiere_planche_planche'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='noteects',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='eleve',
            name='cube',
            field=models.BooleanField(default=False, verbose_name='redoublant'),
        ),
        migrations.AddField(
            model_name='noteects',
            name='cube',
            field=models.BooleanField(default=False, verbose_name='cube'),
        ),
        migrations.AlterField(
            model_name='noteglobaleects',
            name='annee',
            field=models.PositiveSmallIntegerField(choices=[(1, '1ère année'), (2, '2ème année'), (3, '3eme année')], verbose_name='année'),
        ),
        migrations.AlterUniqueTogether(
            name='noteects',
            unique_together={('eleve', 'matiere', 'semestre', 'cube')},
        ),
    ]
