# Generated by Django 4.2 on 2025-10-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0031_alter_noteects_unique_together_eleve_cube_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='cacherang',
            field=models.BooleanField(default=False, verbose_name='masquer les rangs des étudiants'),
        ),
    ]
