# Generated by Django 4.2 on 2026-05-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0032_prof_cacherang'),
    ]

    operations = [
        migrations.AddField(
            model_name='planche',
            name='commentaire_colleur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
